allowBuilds:
  electron-winstaller: true
minimumReleaseAgeExclude:
  - electron@43.0.0
overrides:
  music-metadata: ">=11.12.2"
  file-type: ">=21.3.1"
onlyBuiltDependencies:
  - electron-winstaller
  - electron
  - rcedit
